version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    dep-updates:
      dependency-type: "production"
      applies-to: "version-updates"
    dev-updates:
      dependency-type: "development"
      applies-to: "version-updates"
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    dep-updates:
      dependency-type: "production"
      applies-to: "version-updates"
    dev-updates:
      dependency-type: "development"
      applies-to: "version-updates"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    dep-updates:
      dependency-type: "production"
      applies-to: "version-updates"
    dev-updates:
      dependency-type: "development"
      applies-to: "version-updates"
