[package]
name = "krata-xengnt"
description = "An implementation of xen grant interfaces for krata."
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
thiserror = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["ioctl"] }

[lib]
name = "xengnt"
